/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Active categories, optionally for one listing kind. */
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["conversations_list"];
        put?: never;
        post: operations["conversations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["conversations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["conversations_messages_retrieve"];
        put?: never;
        post: operations["conversations_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["conversations_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/unread-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["conversations_unread_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Post an item listing at the seller's school. Photos are sent as repeated `photos`
         *     files, in order.
         */
        post: operations["listings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Any signed-in student can fetch a listing, whatever its school. */
        get: operations["listings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put: operations["me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/schools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public directory of schools known to Tanu and their marketplace state. */
        get: operations["schools_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schools/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public directory of schools known to Tanu and their marketplace state. */
        get: operations["schools_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/follow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_follow_create"];
        delete: operations["users_follow_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        Category: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
        };
        /**
         * @description * `black` - Black
         *     * `white` - White
         *     * `gray` - Gray
         *     * `brown` - Brown
         *     * `beige` - Beige
         *     * `red` - Red
         *     * `pink` - Pink
         *     * `orange` - Orange
         *     * `yellow` - Yellow
         *     * `green` - Green
         *     * `blue` - Blue
         *     * `purple` - Purple
         *     * `gold` - Gold
         *     * `silver` - Silver
         *     * `multi` - Multicolor
         * @enum {string}
         */
        ColorEnum: "black" | "white" | "gray" | "brown" | "beige" | "red" | "pink" | "orange" | "yellow" | "green" | "blue" | "purple" | "gold" | "silver" | "multi";
        /**
         * @description * `new_with_tags` - New with tags
         *     * `like_new` - Like new
         *     * `good` - Good
         *     * `fair` - Fair
         *     * `poor` - Poor
         * @enum {string}
         */
        ConditionEnum: "new_with_tags" | "like_new" | "good" | "fair" | "poor";
        Conversation: {
            readonly id: number;
            readonly other_user: components["schemas"]["MessagingUser"];
            readonly latest_message: components["schemas"]["Message"];
            readonly unread_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            last_message_at?: string | null;
        };
        CurrentUser: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly username: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly school: components["schemas"]["School"];
            instagram_handle?: string | null;
            profile_description?: string;
            readonly follower_count: number;
            readonly following_count: number;
        };
        CurrentUserRequest: {
            instagram_handle?: string | null;
            profile_description?: string;
        };
        ItemDetails: {
            readonly condition: components["schemas"]["ConditionEnum"];
            readonly size: string;
            readonly brand: string;
            readonly color: components["schemas"]["ColorEnum"] | components["schemas"]["BlankEnum"];
        };
        /**
         * @description * `item` - Item
         *     * `service` - Service
         * @enum {string}
         */
        KindEnum: "item" | "service";
        /** @description A listing as returned by the API. */
        Listing: {
            readonly id: number;
            readonly kind: components["schemas"]["KindEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            readonly title: string;
            readonly description: string;
            readonly price_cents: number;
            readonly currency: string;
            readonly category: components["schemas"]["Category"];
            readonly school: components["schemas"]["SchoolSummary"];
            readonly seller: components["schemas"]["SellerSummary"];
            readonly item_details: components["schemas"]["ItemDetails"] | null;
            readonly photos: components["schemas"]["ListingPhoto"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Multipart input for creating an item listing. Kind, school, currency and status are set
         *     by the server, so they aren't fields here and are ignored if sent.
         */
        ListingCreateRequest: {
            category: number;
            title: string;
            /** @default  */
            description: string;
            price_cents: number;
            condition: components["schemas"]["ConditionEnum"];
            /** @default  */
            size: string;
            /** @default  */
            brand: string;
            /** @default  */
            color: components["schemas"]["ColorEnum"] | components["schemas"]["BlankEnum"];
            /** @description 1 to 10 JPEG, PNG or WebP files of up to 10 MB each, in order. The first is the cover. */
            photos: string[];
        };
        ListingPhoto: {
            readonly id: number;
            readonly position: number;
            readonly image_url: string;
        };
        MarkReadRequest: {
            message_id?: number;
        };
        /**
         * @description * `planned` - Planned
         *     * `waitlist` - Waitlist
         *     * `open` - Open
         *     * `paused` - Paused
         * @enum {string}
         */
        MarketplaceStatusEnum: "planned" | "waitlist" | "open" | "paused";
        Message: {
            readonly id: number;
            readonly conversation: number;
            readonly sender: components["schemas"]["MessagingUser"];
            readonly body: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly is_mine: boolean;
        };
        MessagePage: {
            readonly messages: components["schemas"]["Message"][];
            readonly has_more: boolean;
        };
        MessagingUser: {
            readonly id: number;
            username: string;
            first_name?: string;
            readonly school: components["schemas"]["School"];
        };
        PatchedCurrentUserRequest: {
            instagram_handle?: string | null;
            profile_description?: string;
        };
        PublicUser: {
            readonly id: number;
            username: string;
            first_name?: string;
            readonly school: components["schemas"]["School"];
            instagram_handle?: string;
            profile_description?: string;
            readonly follower_count: number;
            readonly following_count: number;
            readonly is_following: boolean;
            readonly is_self: boolean;
        };
        PublicUserRequest: {
            username: string;
            first_name?: string;
            instagram_handle?: string;
            profile_description?: string;
        };
        School: {
            name: string;
            short_name: string;
            slug: string;
            signup_is_open?: boolean;
            marketplace_status?: components["schemas"]["MarketplaceStatusEnum"];
            city?: string;
            state?: string;
            country_code?: string;
            timezone?: string;
            readonly domains: string[];
        };
        SchoolRequest: {
            name: string;
            short_name: string;
            slug: string;
            signup_is_open?: boolean;
            marketplace_status?: components["schemas"]["MarketplaceStatusEnum"];
            city?: string;
            state?: string;
            country_code?: string;
            timezone?: string;
        };
        SchoolSummary: {
            readonly id: number;
            readonly short_name: string;
        };
        SellerSummary: {
            readonly id: number;
        };
        SendMessageRequest: {
            body: string;
        };
        StartConversationRequest: {
            username: string;
        };
        /**
         * @description * `available` - Available
         *     * `pending` - Pending
         *     * `sold` - Sold
         *     * `removed` - Removed
         * @enum {string}
         */
        StatusEnum: "available" | "pending" | "sold" | "removed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_list: {
        parameters: {
            query?: {
                /** @description Only this listing kind. */
                kind?: "item" | "service";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    conversations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    conversations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConversationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StartConversationRequest"];
                "multipart/form-data": components["schemas"]["StartConversationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    conversations_messages_retrieve: {
        parameters: {
            query?: {
                after_id?: number;
                before_id?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
        };
    };
    conversations_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SendMessageRequest"];
                "multipart/form-data": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    conversations_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkReadRequest"];
                "multipart/form-data": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    conversations_unread_count_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ListingCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    listings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CurrentUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CurrentUserRequest"];
                "multipart/form-data": components["schemas"]["CurrentUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCurrentUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCurrentUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedCurrentUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    schools_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"][];
                };
            };
        };
    };
    schools_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"][];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
        };
    };
    users_follow_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PublicUserRequest"];
                "multipart/form-data": components["schemas"]["PublicUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicUser"];
                };
            };
        };
    };
    users_follow_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
