/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put: operations["me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/schools/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public directory of schools known to Tanu and their marketplace state. */
        get: operations["schools_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schools/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public directory of schools known to Tanu and their marketplace state. */
        get: operations["schools_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CurrentUser: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly username: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly school: components["schemas"]["School"];
            instagram_handle?: string | null;
            profile_description?: string;
        };
        /**
         * @description * `planned` - Planned
         *     * `waitlist` - Waitlist
         *     * `open` - Open
         *     * `paused` - Paused
         * @enum {string}
         */
        MarketplaceStatusEnum: "planned" | "waitlist" | "open" | "paused";
        PatchedCurrentUser: {
            readonly id?: number;
            /** Format: email */
            readonly email?: string;
            readonly username?: string;
            readonly first_name?: string;
            readonly last_name?: string;
            readonly school?: components["schemas"]["School"];
            instagram_handle?: string | null;
            profile_description?: string;
        };
        School: {
            name: string;
            short_name: string;
            slug: string;
            signup_is_open?: boolean;
            marketplace_status?: components["schemas"]["MarketplaceStatusEnum"];
            city?: string;
            state?: string;
            country_code?: string;
            timezone?: string;
            readonly domains: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CurrentUser"];
                "application/x-www-form-urlencoded": components["schemas"]["CurrentUser"];
                "multipart/form-data": components["schemas"]["CurrentUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCurrentUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCurrentUser"];
                "multipart/form-data": components["schemas"]["PatchedCurrentUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    schools_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"][];
                };
            };
        };
    };
    schools_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
}
