# Generated by Django 6.1.1 on 2026-10-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_marketplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='timezone',
        ),
    ]
