# Generated by Django 6.1.1 on 2026-10-02 04:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], default='item', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('removed', 'Removed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='listings.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='item_details', serialize=False, to='listings.listing')),
                ('condition', models.CharField(choices=[('new_with_tags', 'New with tags'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('brown', 'Brown'), ('beige', 'Beige'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('gold', 'Gold'), ('silver', 'Silver'), ('multi', 'Multicolor')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'item details',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service_details', serialize=False, to='listings.listing')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('location_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('provider_place', "Provider's off-campus place"), ('client_place', "Client's off-campus place"), ('licensed_shop', 'Licensed shop'), ('remote', 'Remote')], max_length=20), blank=True, default=list)),
                ('license_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'service details',
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='schools.school'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['school', 'status', '-created_at'], name='listing_feed_idx'),
        ),
    ]
