# Generated by Django 6.1.1 on 2026-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='removed_by',
            field=models.CharField(blank=True, choices=[('seller', 'Seller'), ('moderation', 'Moderation')], max_length=20),
        ),
    ]
