# Generated by Django 6.1.1 on 2026-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_seed_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='listings/thumbnails/%Y/%m/'),
        ),
    ]
