# Generated by Django 6.1.1 on 2026-10-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingphoto_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['kind', 'sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
